
name: ci-golang
on:
  pull_request:
    branches:
      - main
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.14','1.15']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.version }}
      - run: go run math.go
